apiVersion: v1
kind: Service
metadata:
  name: platform-service-node-port
spec:
  type: NodePort
  selector:
    app: platformservice
  ports:
  - name: platformservice
    port: 80
    targetPort: 80
    protocol: TCP