apiVersion: v1
kind: Service
metadata:
  name: platform-service-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: platformservice
  ports:
  - name: platformservice
    port: 80
    targetPort: 80
    protocol: TCP